name: page_curl
description: Page curling effect in Flutter
version: 0.0.1
authors:
  - Jyotirmoy Paul <mr.jyotirmoy.paul@gmail.com>
homepage: https://github.com/jyotirmoy-paul/page_curl
maintainer: Jyotirmoy Paul (@jyotirmoy-paul)

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
